TERMUX_PKG_HOMEPAGE=https://github.com/ptitSeb/box86
TERMUX_PKG_DESCRIPTION="Linux Userspace x86 Emulator with a twist"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="@termux-pacman"
TERMUX_PKG_VERSION=0.4.0
TERMUX_PKG_SRCURL=https://github.com/ptitSeb/box64/archive/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=4504b0df2d9ccfcf15b4d0c80664e216dc1170a4f8caeca46e79b93ff47e5e87
TERMUX_PKG_DEPENDS="gcc-libs-glibc"
TERMUX_PKG_EXCLUDED_ARCHES="aarch64, x86_64, i686"
TERMUX_CMAKE_BUILD="Unix Makefiles"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DARM_DYNAREC=ON
-DCMAKE_BUILD_TYPE=RelWithDebInfo
-DCMAKE_HOST_SYSTEM_PROCESSOR=${TERMUX_ARCH}
"
